In [3]:
from inflection import singularize, pluralize
from collections import OrderedDict


def merge_predictions_in_concept_level(uniform_funcion, words, top_k=None ):
    '''
    uniform_function: either signualarize or pluralize 
    '''
    words_uniformed = [uniform_funcion(word) for word in words]
    concepts = list(OrderedDict.fromkeys(words_uniformed))
    return concepts[:top_k] if top_k is not None else concepts

words = ['fruits', 'things', 'fruit', 'vegetables', 'dates', 'agriculture', 'items', 'crops', 'greens', 'grains']
concepts = merge_predictions_in_concept_level(singularize, words)
print(concepts)

['fruit', 'thing', 'vegetable', 'date', 'agriculture', 'item', 'crop', 'green', 'grain']

In [1]:
# path = 'exp_data_results_anchor_type_Coordinate_remove_Y_PUNC_FULL_concate_or_single_max_anchor_num_10_anchor_scorer_probAvg_filter_obj_True_filter_objects_with_input_True_wnp_False_cpt_False.HYPERNYMSUITE.csv'
import pandas as pd

pd.set_option('display.max_columns',100)
pd.set_option('display.max_colwidth',500)

path = '../log/moment/exp_data_results_anchor_type_Coordinate_remove_Y_PUNC_FULL_concate_or_single_max_anchor_num_10_anchor_scorer_probAvg_filter_obj_True_filter_objects_with_input_True_wnp_False_cpt_False.HYPERNYMSUITE.csv'

df = pd.read_csv(path)
# for x in df.columns:
#     if 'ap' in x:
#         print(x)
display(df[['ap5_lsp_sap', 'ap5_lsp_dap']].mean())

query_cols = ['sub_label', 'obj_label', 'subj_anchors_sg', 'subj_anchors_pl','obj_mask_lsp_sap', 'obj_mask_lsp_dap', 'ap5_lsp_sap', 'ap5_lsp_dap']

df = df.query("ap5_lsp_sap > ap5_lsp_dap")
df = df[query_cols]
# df['things_rank_lsp_dap'] = df['']
display(df.sample(20))
# df[]
# df.head()

ap5_lsp_sap    0.274133
ap5_lsp_dap    0.240683
dtype: float64

,sub_label,obj_label,subj_anchors_sg,subj_anchors_pl,obj_mask_lsp_sap,obj_mask_lsp_dap,ap5_lsp_sap,ap5_lsp_dap
69,elephants,"['animal', 'beast', 'creature', 'mammal', 'herbivore', 'chordate', 'vertebrate']","['lion', 'tiger', 'deer', 'horse', 'bear']","['lions', 'tigers', 'deer', 'horses', 'bears']","['animal', 'mammal', 'thing', 'wildlife', 'creature', 'fauna', 'livestock', 'reptile', 'bird', 'specie']","['animal', 'wildlife', 'mammal', 'thing', 'livestock', 'specie', 'lion', 'game', 'snake', 'creature']",0.520000,0.333333
75,forks,"['tool', 'utensil', 'cutlery', 'tableware', 'object', 'kitchenware', 'artifact', 'artefact']","['knife', 'texas', 'ohio', 'colorado', 'minnesota']","['knives', 'texases', 'ohio', 'colorado', 'minnesota']","['thing', 'knife', 'tool', 'item', 'object', 'shape', 'place', 'instrument', 'poem', 'yes']","['knife', 'minnesota', 'place', 'tool', 'ohio', 'location', 'thing', 'city', 'colorado', 'implement']",0.146667,0.050000
136,pistols,"['firearm', 'gun', 'arm', 'object', 'implement', 'artefact', 'artifact', 'device', 'weapon']","['rifle', 'knife', 'gun', 'ammunition', 'sword']","['rifles', 'knives', 'guns', 'ammunitions', 'swords']","['weapon', 'firearm', 'gun', 'thing', 'implement', 'ammunition', 'weaponry', 'tool', 'item', 'rifle']","['weapon', 'thing', 'firearm', 'item', 'ammunition', 'gun', 'supply', 'accessory', 'implement', 'equipment']",0.760000,0.333333
145,rats,"['chordate', 'vertebrate', 'mammal', 'rodent', 'creature', 'animal', 'beast']","['mouse', 'yes', 'maybe', 'dog', 'probably']","['mice', 'yeses', 'maybes', 'dogs', 'probably']","['animal', 'rodent', 'thing', 'mammal', 'creature', 'people', 'human', 'insect', 'mouse', 'cat']","['thing', 'animal', 'rodent', 'dog', 'mammal', 'yes', 'cat', 'creature', 'predator', 'stuff']",0.710000,0.353333
21,bowls,"['artifact', 'container', 'artefact', 'vessel', 'dishware', 'object', 'kitchenware', 'cookware', 'utensil']","['plate', 'cup', 'pitcher', 'dish', 'yes']","['plates', 'cups', 'pitchers', 'dishes', 'yeses']","['thing', 'object', 'item', 'container', 'dish', 'game', 'sport', 'cup', 'implement', 'vessel']","['thing', 'item', 'container', 'dish', 'food', 'object', 'liquid', 'cup', 'implement', 'vessel']",0.200000,0.066667
34,catfish,"['fish', 'food', 'creature', 'seafood', 'chordate', 'vertebrate', 'animal']","['bass', 'carp', 'shrimp', 'perch', 'alligator']","['basses', 'carp', 'shrimp', 'perches', 'alligators']","['fish', 'specie', 'animal', 'thing', 'reptile', 'fishery', 'bass', 'invertebrate', 'aquatic', 'freshwater']","['fish', 'specie', 'reptile', 'snake', 'seafood', 'thing', 'animal', 'fishing', 'fishery', 'shrimp']",0.333333,0.280000
44,cloaks,"['clothing', 'commodity', 'artifact', 'object', 'apparel', 'artefact', 'garment', 'good', 'wear', 'clothes', 'covering']","['hat', 'glove', 'yes', 'maybe', 'mask']","['hats', 'gloves', 'yeses', 'maybes', 'masks']","['thing', 'clothing', 'accessory', 'clothes', 'garment', 'robe', 'item', 'coat', 'hat', 'hood']","['thing', 'clothing', 'accessory', 'glove', 'costume', 'clothes', 'item', 'garment', 'hat', 'magic']",0.320000,0.100000
30,carp,"['seafood', 'fish', 'chordate', 'vertebrate', 'food', 'creature', 'animal']","['pike', 'roach', 'catfish', 'perch', 'trout']","['pikes', 'roaches', 'catfish', 'perches', 'trout']","['fish', 'thing', 'specie', 'animal', 'reptile', 'freshwater', 'aquatic', 'invertebrate', 'bass', 'fishing']","['fish', 'specie', 'fishing', 'insect', 'thing', 'animal', 'roach', 'pike', 'fishery', 'frog']",0.300000,0.200000
162,sofas,"['artifact', 'furnishing', 'furniture', 'object', 'artefact']","['chair', 'yes', 'cushion', 'table', 'bed']","['chairs', 'yeses', 'cushions', 'tables', 'beds']","['furniture', 'thing', 'chair', 'furnishing', 'item', 'bench', 'place', 'table', 'cushion', 'accessory']","['furniture', 'thing', 'chair', 'item', 'furnishing', 'table', 'cushion', 'bench', 'place', 'accessory']",0.300000,0.280000
10,bears,"['vertebrate', 'chordate', 'mammal', 'predator', 'beast', 'creature', 'animal']","['wolf', 'yes', 'lion', 'tiger', 'cougar']","['wolves', 'yeses', 'lions', 'tigers', 'cougars']","['animal', 'mammal', 'thing', 'predator', 'wildlife', 'people', 'creature', 'dog', 'specie', 'wolf']","['animal', 'cougar', 'predator', 'mammal', 'thing', 'wildlife', 'wolf', 'tiger', 'dog', 'specie']",0.550000,0.483333
116,missiles,"['vehicle', 'arm', 'object', 'weapon', 'artifact', 'artefact', 'device', 'implement', 'rocket']","['rocket', 'bomb', 'artillery', 'torpedo', 'explosive']","['rockets', 'bombs', 'artilleries', 'torpedoes', 'explosives']","['weapon', 'thing', 'explosive', 'artillery', 'rocket', 'ordnance', 'military', 'munition', 'aircraft', 'device']","['weapon', 'thing', 'explosive', 'artillery', 'military', 'equipment', 'defense', 'rocket', 'device', 'item']",0.280000,0.200000
7,bags,"['luggage', 'container', 'object', 'accessory', 'artefact', 'artifact']","['box', 'yes', 'shoe', 'case', 'obviously']","['boxes', 'yeses', 'shoes', 'cases', 'obviously']","['thing', 'item', 'object', 'yes', 'yeah', 'belonging', 'possession', 'clothes', 'clothing', 'accessory']","['thing', 'item', 'yes', 'luggage', 'shoe', 'yeah', 'stuff', 'object', 'clothing', 'container']",0.066667,0.050000
128,penguins,"['animal', 'seabird', 'creature', 'vertebrate', 'chordate', 'bird']","['seal', 'dolphin', 'especially', 'bird', 'duck']","['seals', 'dolphins', 'especially', 'birds', 'ducks']","['animal', 'bird', 'mammal', 'specie', 'creature', 'wildlife', 'thing', 'story', 'reptile', 'seal']","['animal', 'bird', 'specie', 'mammal', 'wildlife', 'whale', 'seal', 'thing', 'creature', 'fauna']",0.520000,0.400000
123,ovens,"['artifact', 'artefact', 'commodity', 'appliance', 'object', 'good', 'device']","['boiler', 'pump', 'refrigerator', 'yes', 'stove']","['boilers', 'pumps', 'refrigerators', 'yeses', 'stoves']","['appliance', 'thing', 'device', 'place', 'heat', 'equipment', 'kitchen', 'bake', 'cook', 'boiler']","['appliance', 'thing', 'boiler', 'device', 'heat', 'equipment', 'cook', 'kitchen', 'stove', 'machinery']",0.333333,0.300000
192,wardrobes,"['object', 'artefact', 'furniture', 'artifact', 'furnishing']","['drawer', 'bathroom', 'furniture', 'shoe', 'clothing']","['drawers', 'bathrooms', 'furnitures', 'shoes', 'clothings']","['thing', 'fashion', 'item', 'clothing', 'furnishing', 'clothes', 'accessory', 'furniture', 'drawer', 'facility']","['thing', 'drawer', 'item', 'clothing', 'facility', 'bathroom', 'furniture', 'cabinet', 'accessory', 'area']",0.040000,0.000000
157,sheep,"['herbivore', 'beast', 'chordate', 'vertebrate', 'ruminant', 'animal', 'mammal', 'creature', 'ungulate']","['goat', 'cattle', 'yes', 'cow', 'horse']","['goats', 'cattle', 'yeses', 'cows', 'horses']","['livestock', 'animal', 'thing', 'cattle', 'mammal', 'people', 'subject', 'creature', 'agriculture', 'specie']","['livestock', 'animal', 'thing', 'cattle', 'rodent', 'specie', 'mammal', 'poultry', 'creature', 'bird']",0.180000,0.100000
191,vultures,"['chordate', 'creature', 'scavenger', 'bird', 'vertebrate', 'raptor', 'animal', 'predator']","['eagle', 'raven', 'hawk', 'owl', 'crow']","['eagles', 'ravens', 'hawks', 'owls', 'crows']","['bird', 'thing', 'animal', 'specie', 'predator', 'insect', 'crow', 'creature', 'falcon', 'people']","['bird', 'specie', 'animal', 'falcon', 'crow', 'hawk', 'eagle', 'thing', 'predator', 'owl']",0.453333,0.333333
67,dressers,"['furnishing', 'object', 'artefact', 'furniture', 'artifact']","['drawer', 'bed', 'cabinet', 'mirror', 'chair']","['drawers', 'beds', 'cabinets', 'mirrors', 'chairs']","['furniture', 'thing', 'item', 'accessory', 'furnishing', 'drawer', 'cabinet', 'object', 'place', 'table']","['furniture', 'thing', 'item', 'drawer', 'cabinet', 'furnishing', 'mirror', 'accessory', 'sink', 'object']",0.280000,0.200000
65,doves,"['creature', 'bird', 'chordate', 'vertebrate', 'animal']","['crow', 'raven', 'pigeon', 'duck', 'eagle']","['crows', 'ravens', 'pigeons', 'ducks', 'eagles']","['bird', 'thing', 'specie', 'pigeon', 'animal', 'people', 'crow', 'creature', 'object', 'example']","['bird', 'specie', 'thing', 'pigeon', 'crow', 'animal', 'duck', 'raven', 'falcon', 'creature']",0.280000,0.200000
3,ants,"['insect', 'arthropod', 'bug', 'creature', 'invertebrate', 'animal']","['bee', 'beetle', 'wasp', 'yes', 'fly']","['bees', 'beetles', 'wasps', 'yeses', 'flies']","['insect', 'animal', 'thing', 'people', 'invertebrate', 'creature', 'specie', 'mammal', 'organism', 'bee']","['insect', 'thing', 'animal', 'bee', 'invertebrate', 'specie', 'creature', 'organism', 'mammal', 'wasp']",0.520000,0.453333

In [8]:
!ls ../log/moment

df1 = pd.read_csv('../log/moment/bless.raw.csv')
df2 = pd.read_csv('../log/moment/bless.wn.csv')

display (df1.head()[['sub_label', 'def_sap', 'obj_mask_def_sap']])
display (df2.head()[['sub_label', 'def_sap', 'obj_mask_def_sap']])

bless.raw.csv
bless.wn.csv
exp_data_results_anchor_type_Coordinate_remove_Y_PUNC_FULL_concate_or_single_max_anchor_num_10_anchor_scorer_probAvg_filter_obj_True_filter_objects_with_input_True_wnp_False_cpt_False.CLSB.csv

,sub_label,def_sap,obj_mask_def_sap
0,acacias,"['An acacia is a [MASK].', 'An acacia is an [MASK].']","['shrub', 'tree', 'plant', 'oak', 'vegetable', 'almond', 'olive', 'arbor', 'hardwood', 'apple']"
1,alligators,"['An alligator is a [MASK].', 'An alligator is an [MASK].']","['animal', 'fish', 'monster', 'snake', 'crocodile', 'turtle', 'human', 'predator', 'frog', 'insect']"
2,ambulances,"['An ambulance is a [MASK].', 'An ambulance is an [MASK].']","['emergency', 'accident', 'car', 'helicopter', 'hospital', 'vehicle', 'machine', 'illusion', 'truck', 'animal']"
3,ants,"['An ant is a [MASK].', 'An ant is an [MASK].']","['animal', 'insect', 'bug', 'specie', 'organism', 'pest', 'parasite', 'bee', 'plant', 'colony']"
4,apples,"['An apple is a [MASK].', 'An apple is an [MASK].']","['tree', 'fruit', 'pear', 'nut', 'vegetable', 'person', 'orange', 'banana', 'berry', 'plum']"

,sub_label,def_sap,obj_mask_def_sap
0,acacias,"['An acacia is a [MASK].', 'An acacia is an [MASK].']","['acacia', 'shrub', 'tree', 'plant', 'oak', 'vegetable', 'almond', 'olive', 'arbor', 'hardwood']"
1,alligators,"['An alligator is a [MASK].', 'An alligator is an [MASK].']","['animal', 'alligator', 'fish', 'monster', 'snake', 'crocodile', 'turtle', 'human', 'predator', 'frog']"
2,ambulances,"['An ambulance is a [MASK].', 'An ambulance is an [MASK].']","['ambulance', 'emergency', 'accident', 'car', 'helicopter', 'hospital', 'vehicle', 'machine', 'illusion', 'truck']"
3,ants,"['An ant is a [MASK].', 'An ant is an [MASK].']","['animal', 'ant', 'insect', 'bug', 'specie', 'organism', 'pest', 'parasite', 'bee', 'plant']"
4,apples,"['An apple is a [MASK].', 'An apple is an [MASK].']","['apple', 'tree', 'fruit', 'pear', 'nut', 'vegetable', 'person', 'orange', 'banana', 'berry']"